---
extra_javascript:
  - jquery.min.js
  - jquery.fancybox.min.js
  - zversions.js
extra_css:
  - extra.css
  - jquery.fancybox.min.css
markdown_extensions:
- meta
- admonition
- footnotes
- meta
- attr_list
- codehilite: {guess_lang: true}
- toc: {permalink: true}
- pymdownx.betterem: {smart_enable: all}
- pymdownx.caret
- pymdownx.critic
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist: {custom_checkbox: true}
- pymdownx.tabbed
- pymdownx.tilde
nav:
- Getting started:
  - ZM1-DB: gettingstarted/ZM1-DB.md
  - 4ZeroBox: gettingstarted/4ZeroBox.md
  - 4ZeroBox Mobile: gettingstarted/4ZeroBox_mobile.md
  - SDK: gettingstarted/sdk_guide.md
- Hardware:
  - {Hardware Platforms: hardware/index.md}
  - IoT Modules:
    - ZM1: hardware/ZM1_module.md
  - Development Boards:
    - ZM1-DB: hardware/ZM1-Development-Board.md
  - Expansion Boards:
    - EXP-CONNECT: hardware/EXP-CON.md
    - EXP-AIN: hardware/EXP-AIN.md
    - EXP-SER: hardware/EXP-SER.md
    - EXP-RELAY: hardware/EXP-RELAY.md
    - EXP-IO: hardware/EXP-IO.md
    - EXP-PROTO: hardware/EXP-PROTO.md
  - Industrial IoT Device and Kit:
    - 4ZeroBox: hardware/4ZeroBox.md
    - 4ZeroBox Mobile: hardware/4ZeroBox_mobile.md
    - {Industrial IoT Kit: hardware/I40Kit.md}
    - {Product Innovation Kit: hardware/productInovv.md}
- Cloud:
  - Features and components: zCloud/index.md
  - Web application interface: zCloud/cloud_interface.md
- Tutorials and demos:
  - {Introduction: tutorials/index.md}
  - Expansion boards:
    - Use cellular connectivity and GPS: tutorials/zm1-db/exp-connect-example.md
    - Control AC and DC devices: tutorials/zm1-db/exp-relay-lamp.md
    - Connect industrial sensors and devices: tutorials/zm1-db/exp-io-temperature.md
    - Prototype modules and sensors: tutorials/zm1-db/ex-proto-bme280.md
    - Communicate over RS232,RS485 and CAN protocol: tutorials/zm1-db/exp-ser-rs485.md
  - tutorials/4zerobox/industrial_kit.md
  - Cloud:
    - Connect to Zerynth Cloud: tutorials/zCloud/connect.md
    - tutorials/zCloud/jobs_relays.md
    - Introduction to FOTA: tutorials/zCloud/FOTA.md
    - FOTA for fleet of devices: tutorials/zCloud/FOTA_fleet.md
    - Integration with 3rd party services: tutorials/zCloud/azure_integration.md
    - Track KPIs and Create Dashboards in Zerynth Cloud: tutorials/zCloud/dashboard.md
  - tutorials/cli.md
- Technical reference:
    - {Introduction: reference/index.md}
    - SDK:
      - Operating System: 
        - reference/os/index.md
        - reference/os/basics.md
        - reference/os/seqmap.md
        - reference/os/pinmap.md
        - reference/os/clang.md
        - reference/os/os.md
      - Development Environment: reference/vscode/index.md
      - Boards and Expansions:
        - reference/libs/expansions/index.md
        - reference/bsp/4zerobox_v9.md
        - reference/bsp/4zerobox_mobile.md
        - reference/bsp/zm1_db.md
        - reference/libs/expansions/exp-io.md
        - reference/libs/expansions/exp-relay.md
        - reference/libs/expansions/exp-ser.md
        - reference/libs/expansions/exp-ain.md
        - reference/libs/expansions/exp-connect.md
      - Standard Library:
        - reference/libs/stdlib/builtins.md
        - reference/libs/stdlib/threading.md
        - reference/libs/stdlib/struct.md
        - reference/libs/stdlib/gc.md
        - reference/libs/stdlib/timers.md
        - reference/libs/stdlib/watchdog.md
        - Time and Dates:
          - reference/libs/stdlib/time.md
          - reference/libs/stdlib/datetime.md
          - reference/libs/stdlib/suntime.md
        - Data Structures:
          - reference/libs/stdlib/fifo.md
          - reference/libs/stdlib/queue.md
        - Serialization:
          - reference/libs/stdlib/base64.md
          - reference/libs/stdlib/json.md
          - reference/libs/stdlib/cbor.md
          - reference/libs/stdlib/csv.md
        - Filesystem:
          - reference/libs/stdlib/fs.md
        - Peripherals:
          - reference/libs/stdlib/serial.md
          - reference/libs/stdlib/gpio.md
          - reference/libs/stdlib/i2c.md
          - reference/libs/stdlib/spi.md
          - reference/libs/stdlib/adc.md
          - reference/libs/stdlib/pwm.md
          - reference/libs/stdlib/can.md
          - reference/libs/stdlib/mcu.md
      - Networking:
        - reference/libs/networking/index.md
        - reference/libs/networking/net.md
        - reference/libs/networking/wifi.md
        - reference/libs/networking/wifisniff.md
        - reference/libs/networking/eth.md
        - reference/libs/networking/cellular.md
        - reference/libs/networking/socket.md
      - Protocols:
        - reference/libs/protocols/index.md
        - reference/libs/protocols/fins.md
        - reference/libs/protocols/http.md
        - reference/libs/protocols/ntp.md
        - reference/libs/protocols/mqtt.md
        - reference/libs/protocols/modbus.md
      - Security and Cryptography:
        - reference/libs/crypto/index.md
        - reference/libs/crypto/element.md
      - Math:
        - reference/libs/math/math.md
        - reference/libs/math/bignum.md
        - reference/libs/math/fft/fft.md
      - Zerynth Device Manager:
        - reference/libs/zerynth/zdm/index.md
        - reference/libs/zerynth/zdm/examples.md
      - Time Series Log:
        - reference/libs/zerynth/tslog/index.md
      - Sensors:
        - reference/libs/zerynth/zsensors/index.md
      - Components:
          - reference/libs/components/index.md
          - reference/libs/components/bme280/index.md
          - reference/libs/components/bmp180/index.md
          - reference/libs/components/bno055/index.md
          - reference/libs/components/mcp2515/index.md
          - reference/libs/components/IIM42652/index.md
          - reference/libs/components/ds1307/index.md
      - Filters:
          - reference/libs/filters/iir.md
      - Command Line Interface:
          - reference/cli/ztc/index.md
          - reference/cli/zdm/index.md
      - FAQ:
          - reference/faq/hardware.md
          - reference/faq/installer.md
          - reference/faq/vscode.md
          - reference/faq/filesystem.md
      - SDK Examples:
          - reference/examples/zerynth-os/hello_zerynth.md
          - reference/examples/zerynth-os/multi_serial.md
          - reference/examples/zerynth-os/multi_thread_basic.md
          - reference/examples/zerynth-os/c_language_interface.md
          - reference/examples/zerynth-os/adc.md
          - reference/examples/zerynth-os/watchdog.md
    - Cloud APIs:
      - reference/api/authentication/index.md
      - reference/api/zdm/index.md
      - reference/api/zstorage/index.md
      - reference/api/apps/index.md
    - Changelog: reference/changelogs/index.md
    - What's new in SDK v3.x: reference/changelogs/whatsnew.md
- Partners:
  - Zerynth Platform:
    - {Introduction: partners/zerynth_platform/index.md}
    - Platform Architecture:  partners/zerynth_platform/platform_architecture/placeholder.md
  - Zerynth App:
    - {Introduction: partners/zerynth_app/index.md}
    - Machine Monitoring: partners/zerynth_app/machine_monitoring/placeholder.md
    - Production Insight: partners/zerynth_app/production_insight/placeholder.md
    - Machine Control: partners/zerynth_app/machine_control/placeholder.md
    - Custom Dashboarding: partners/zerynth_app/custom_dashboarding/placeholder.md
    - Reports: partners/zerynth_app/reports/placeholder.md
    - Rules: partners/zerynth_app/rules/placeholder.md
    - Tools: partners/zerynth_app/tools/placeholder.md
  - Machines Connection and Management:
    - Machines Connection and Management: partners/machines_connection_and_management/machines_connection_and_management/placeholder.md
  - Edge Layer:
    - {Introduction: partners/edge_layer/index.md}
    - Industrial IOT Kit:
      - Essential: partners/edge_layer/industrial_iot_kit/essential.md
      - Electric Panel: partners/edge_layer/industrial_iot_kit/electric_panel.md
  - Integrations:
    - Webhook: partners/integrations/integrations/webhook.md
  - Other Settings:
    - Other Settings: partners/other_settings/other_settings/placeholder.md
  - Wiring Guide:
    - {Introduction: partners/wiring_guide/index.md}
    - Wiring Guide: partners/wiring_guide/wiring_guide.md



plugins:
- search
- minify: {minify_html: true}
site_name: Zerynth Documentation
theme:
    custom_dir: material
    favicon: images/favicon.png
    features:
      - navigation.tabs
    font: {code: roboto, text: Open Sans}
    logo: images/favicon-white.png
    name: material
    palette: {accent: red, primary: indigo}
...
